version: "3.8"

services:
  mysql-container:
    image: mysql:8.0
    container_name: marvel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: marvel1234
      MYSQL_DATABASE: marvel
      MYSQL_USER: marvel1234
      MYSQL_PASSWORD: marvel1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
