
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marvel
    username: marvel1234
    password: marvel1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect